# ==========================================
# AUTO GROUP CONFIG:
# ==========================================

# Enable Auto Group
# Default: true
gameserver.autogroup.enable = false

# ==========================================
# Idgel Dome 6.x:
# ==========================================
# Enable Idgel Dome 6.x
# Default: true
gameserver.idgel.dome.enable = false

# Idgel Dome 6.x Registration.
# Default: 60 min
gameserver.idgel.dome.timer = 60
# Default: 300 min
gameserver.idgel.dome.timer2 = 300

# Idgel Dome 6.x Time Entry
# Midday: 0 0 12 ? * TUE,FRI,SUN *
# Night: 0 0 20 ? * TUE,FRI,SUN *
gameserver.idgel.dome.schedule.midday = 0 0 12 ? * TUE,FRI,SUN *
gameserver.idgel.dome.schedule.night = 0 0 20 ? * TUE,FRI,SUN *

# ==========================================
# Ashunatal Dredgion 6.x:
# ==========================================
# Enable Ashunatal Dredgion 6.x
# Default: true
gameserver.ashunatal.dredgion.enable = false

# Ashunatal Dredgion 6.x Registration.
# Default: 60 min
gameserver.ashunatal.dredgion.timer = 60
# Default: 300 min
gameserver.ashunatal.dredgion.timer2 = 300

# Ashunatal Dredgion 6.x Time Entry
# Midday: 0 0 12 ? * MON,THU,SUN *
# Night: 0 0 20 ? * MON,THU,SUN *
gameserver.ashunatal.schedule.midday = 0 0 12 ? * MON,THU,SUN *
gameserver.ashunatal.schedule.night = 0 0 20 ? * MON,THU,SUN *

# ==========================================
# Illumiel Brawl 6.x:
# ==========================================
# Enable Illumiel Brawl 6.x
# Default: true
gameserver.illumiel.enable = false

# Illumiel Brawl 6.x Registration.
# Default: 180 min
gameserver.illumiel.timer = 180
# Default: 420 min
gameserver.illumiel.timer2 = 420

# Illumiel Brawl 6.x Time Entry
# Midday: 0 0 11 ? * TUE,THU,SAT,SUN *
# Night: 0 0 19 ? * TUE,THU,SAT,SUN *
gameserver.illumiel.schedule.midday = 0 0 11 ? * TUE,THU,SAT,SUN *
gameserver.illumiel.schedule.night = 0 0 19 ? * TUE,THU,SAT,SUN *

# ==========================================
# Kamar Battlefield 7.x:
# ==========================================
# Enable Kamar Battlefield 7.x
# Default: true
gameserver.kamar.enable = false

# Kamar Battlefield 7.x Registration.
# Default: 60 min
gameserver.kamar.timer = 60
# Default: 300 min
gameserver.kamar.timer2 = 300

# Kamar Battlefield 7.x Time Entry
# Midday: 0 0 12 ? * SAT *
# Night: 0 0 20 ? * SAT *
gameserver.kamar.schedule.midday = 0 0 12 ? * SAT *
gameserver.kamar.schedule.night = 0 0 20 ? * SAT *