# ======================================
# ENCHANT CONFIG:
# ======================================

# Clean items with overloaded manastones
# Default: false
gameserver.manastone.clean = false

# Enchant Cast Speed Item:
# Default: 2000
gameserver.enchant.cast.speed = 2000