# ============================
# Housing Confi's:
# ============================

# House render visibility range; The bigger value, 
# the more packets will be sent during login.
# Default: 200
gameserver.housing.visibility.distance = 200

# Enable show house door editor id (the same as in house name)
# Default: true
gameserver.housedoor.showid = true

# Minimum access level to allow enter houses
# Default: 5
gameserver.housedoor.accesslevel = 5

# Auction for houses
# Default: true
gameserver.housing.auction.enable = true

# Pay rent
# Default: true
gameserver.housing.pay.enable = true

# Auction Day/Time
# Default: 0 0 0 ? * MON
gameserver.housing.auction.time = 0 0 0 ? * MON

# Day/time until registering houses in auction is allowed for players 
# Default: 0 0 12 ? * SUN
gameserver.housing.auction.registerend = 0 0 12 ? * SUN

# House maintenance frequency
# Default: 0 0 0 ? * MON
gameserver.housing.maintain.time = 0 0 0 ? * MON

# Auction bid step limit (bid can not exceed 100% of the current price)
# Default: 100%
gameserver.housing.auction.steplimit = 100

# Auction Price:
gameserver.housing.auction.default_bid.house = 1200000
gameserver.housing.auction.default_bid.mansion = 11200000
gameserver.housing.auction.default_bid.estate = 33500000
gameserver.housing.auction.default_bid.palace = 100000000

# Auction Level:
gameserver.housing.auction.bidding.min_level.house = 21
gameserver.housing.auction.bidding.min_level.mansion = 30
gameserver.housing.auction.bidding.min_level.estate = 40
gameserver.housing.auction.bidding.min_level.palace = 50

# Default refund percentage after a (lost) auction (0.3f = 30%)
gameserver.housing.auction.default_refund = 0.3f

# Output script content to log
# Default: false
gameserver.housing.scripts.debug = false

# If enabled - housing broker will be filled automatically
# according to next settings.
# http://aion.wikia.com/wiki/Housing
# Default: true
gameserver.housing.auction.fill.auto = true

gameserver.housing.auction.fill.auto.houses = 484
gameserver.housing.auction.fill.auto.mansion = 314
gameserver.housing.auction.fill.auto.estate = 254
gameserver.housing.auction.fill.auto.palace = 8