# ============================
# Jumping Confi's:
# ============================

# Enable "Jumping System"
# Default: false
gameserver.enable.jumping = false

# At what level will the player be, if the player use the "Jumping"
# Default: 80
gameserver.jumping.player.level = 80

# At which level "Jumping" will be activated.
# Default: 80
gameserver.jumping.min.level = 80