<?xml version="1.0" encoding="UTF-8"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:include schemaLocation="../modifiers.xsd"/>
    <xs:include schemaLocation="../stats/stats.xsd"/>
    <xs:include schemaLocation="../import.xsd"/>
    <xs:element name="quest_rnd_rewards">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="quest_rnd_reward" type="QuestRndRewards" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:complexType name="QuestRndRewards">
        <xs:sequence>
            <xs:element name="rnd_reward" type="RndRewards" minOccurs="0" maxOccurs="unbounded"/>
        </xs:sequence>
		<xs:attribute name="id" type="xs:int"/>
    </xs:complexType>
	<xs:complexType name="RndRewards">
        <xs:attribute name="item_id" type="xs:int"/>
		<xs:attribute name="count" type="xs:int" default="1"/>
    </xs:complexType>
</xs:schema>