<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<xs:schema version="1.0" xmlns:xs="http://www.w3.org/2001/XMLSchema">
    <xs:element name="skin_skills">
        <xs:complexType>
            <xs:sequence>
                <xs:element name="skin_skill" minOccurs="0" maxOccurs="unbounded">
                    <xs:complexType>
                        <xs:sequence/>
                        <xs:attribute name="id" type="xs:int" use="required"/>
                        <xs:attribute name="name" type="xs:string"/>
                        <xs:attribute name="desc" type="xs:string"/>
                        <xs:attribute name="skill_group" type="xs:string" use="required"/>
						<xs:attribute name="motion_name" type="xs:string" use="required"/>
                        <xs:attribute name="ammo_speed" type="xs:int" use="required"/>
                    </xs:complexType>
                </xs:element>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
</xs:schema>