package com.aionemu.gameserver.model.templates.item;

public enum EnchantType
{
	PVP,
	PVE,
	GRIND,
	ENCHANT,
	AUTHORIZE,
	DESTRUCTION,
	ENCHANT_ANCIENT_ANCIENT,
	ENCHANT_RELIC_ANCIENT,
	ENCHANT_FINALITY_ANCIENT,
	ENCHANT_MATTER_ENCHANT_PVE_ANCIENT;
}